const Data = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/84XPpjGvxNyExjSuLQe0SzioErt.jpg",
      id: 1396,
      name: "Breaking Bad",
      original_language: "en",
      original_name: "Breaking Bad",
      overview:
        "When Walter White, a New Mexico chemistry teacher, is diagnosed with Stage III cancer and given a prognosis of only two years left to live. He becomes filled with a sense of fearlessness and an unrelenting desire to secure his family's financial future at any cost as he enters the dangerous world of drugs and crime.",
      poster_path: "/ggFHVNu6YYI5L9pCfOacjizRGt.jpg",
      media_type: "tv",
      genre_ids: [18, 80],
      popularity: 231.61,
      first_air_date: "2008-01-20",
      vote_average: 8.885,
      vote_count: 11954,
      origin_country: ["US"],
    },
    {
      adult: false,
      backdrop_path: "/yzpZVgaTZzDrAP1yVeCbKZH9jmA.jpg",
      id: 559969,
      title: "El Camino: A Breaking Bad Movie",
      original_language: "en",
      original_title: "El Camino: A Breaking Bad Movie",
      overview:
        "In the wake of his dramatic escape from captivity, Jesse Pinkman must come to terms with his past in order to forge some kind of future.",
      poster_path: "/ePXuKdXZuJx8hHMNr2yM4jY2L7Z.jpg",
      media_type: "movie",
      genre_ids: [80, 18, 53, 28],
      popularity: 27.272,
      release_date: "2019-10-11",
      video: false,
      vote_average: 6.942,
      vote_count: 4345,
    },
    {
      adult: false,
      backdrop_path: "/27JyB13Wr2KEVUIKjtw9x669I39.jpg",
      id: 239459,
      title: "No Half Measures: Creating the Final Season of Breaking Bad",
      original_language: "en",
      original_title:
        "No Half Measures: Creating the Final Season of Breaking Bad",
      overview:
        "A documentary about the making of season five of the acclaimed AMC series Breaking Bad.",
      poster_path: "/j2QNxbsCabpFQG7KkLYpkFz6IWk.jpg",
      media_type: "movie",
      genre_ids: [99],
      popularity: 17.341,
      release_date: "2013-11-26",
      video: false,
      vote_average: 8.4,
      vote_count: 99,
    },
    {
      adult: false,
      backdrop_path: "/mR04QRFtok3EJn4fMBrCvi5xOeh.jpg",
      id: 1089398,
      title: "Daniel Brühl: Breaking Bad",
      original_language: "de",
      original_title: "Daniel Brühl – Der Reiz des Bösen",
      overview:
        "A portrait of the Spanish-German actor Daniel Brühl, a versatile performer capable of moving easily from the gentlest to the darkest role.",
      poster_path: "/kxwtTdHquKObHiT8LAWsHDQricj.jpg",
      media_type: "movie",
      genre_ids: [99, 10770],
      popularity: 2.466,
      release_date: "2023-02-19",
      video: false,
      vote_average: 0.0,
      vote_count: 0,
    },
    {
      adult: false,
      backdrop_path: "/fAh0hIYSqaoryl97l1bKP5rVQZP.jpg",
      id: 675519,
      title: "Snow Globe: A Breaking Bad Short",
      original_language: "en",
      original_title: "Snow Globe: A Breaking Bad Short",
      overview:
        "Todd finds the courage to reach out to his Breaking Bad co-conspirator Lydia with a very important question.",
      poster_path: "/uPxxAXfpuCDDIsaS4srPjwVMO1C.jpg",
      media_type: "movie",
      genre_ids: [35, 80],
      popularity: 1.083,
      release_date: "2020-02-16",
      video: false,
      vote_average: 5.5,
      vote_count: 4,
    },
    {
      adult: false,
      backdrop_path: "/mZP6RmsSUAA46s1Dl1tjhCzhTUs.jpg",
      id: 19050,
      title: "The Bad News Bears in Breaking Training",
      original_language: "en",
      original_title: "The Bad News Bears in Breaking Training",
      overview:
        "A troubled, rebellious teen drives his rambunctious baseball team out to Houston where they play an exhibition game and the boy meets his estranged father, and hires him as the teams coach.",
      poster_path: "/cAwVRX1EsnSKzvo5HEA4S2rBoDA.jpg",
      media_type: "movie",
      genre_ids: [35, 10751],
      popularity: 4.955,
      release_date: "1977-07-08",
      video: false,
      vote_average: 5.848,
      vote_count: 33,
    },
    {
      adult: false,
      backdrop_path: "/wKRXQ9OWXNwmRyIgLMULkedKtiU.jpg",
      id: 635602,
      title: "Breaking Bad Wolf",
      original_language: "en",
      original_title: "Breaking Bad Wolf",
      overview:
        "Veteran cop John Mark Dougan left the force, appalled by corruption within. He started a forum for honest cops to anonymously expose police the bad. Fierce backlash eventually forced Dougan to flee the US and seek refuge in Russia.",
      poster_path: "/bKiGcZ13r8nkYiuKUBakbzAjmwn.jpg",
      media_type: "movie",
      genre_ids: [99],
      popularity: 0.6,
      release_date: "",
      video: true,
      vote_average: 10.0,
      vote_count: 1,
    },
    {
      adult: false,
      backdrop_path: "/qyVxRsc5RKF85ejeSnT3MO4gwLX.jpg",
      id: 934809,
      title:
        "The Road to El Camino: Behind the Scenes of El Camino: A Breaking Bad Movie",
      original_language: "en",
      original_title:
        "The Road to El Camino: Behind the Scenes of El Camino: A Breaking Bad Movie",
      overview:
        'Aaron Paul, Vince Gilligan and other cast members, producers and crew share stories and footage from the making of "El Camino."',
      poster_path: "/josprjZSPHwK372KQTJctgoRynV.jpg",
      media_type: "movie",
      genre_ids: [99],
      popularity: 4.15,
      release_date: "2019-10-28",
      video: false,
      vote_average: 7.3,
      vote_count: 10,
    },
  ],
  total_pages: 1,
  total_results: 8,
};
export default Data;
